### ISSUE TITLE
[Bug] (Docker-Compose Installation) | using a host volume the container folder is empty

### ISSUE THREAD

**Issue by scharez** [FOSSBilling/Docker#5]
### Describe the bug

Hi,

when i install fossbilling via docker compose and mount the volume to e.g /opt/fossbilling/html:/var/www/html --> the folder inside the container becomes empty.

### How to reproduce

1. Use the docker-compse file as mentioned in the docs
2. Edit the file and use a host volume eg /opt/fossbilling/html:/var/www/html

### Expected behavior

Folder becomes empty

### FOSSBilling version

the latest release

### Device

Desktop

**Comment by admdly** [comment]
Apologies for the delay in responding to this, but it appears you have misunderstood the format of the `volumes` option in `docker-compose.yml`. This should not be a path on the system, but a named volume within Docker. 

If you use our suggested `docker-compose.yml`, the correct value for volumes is `fossbilling:/var/www/html`. However, you are free to create another volume and use this as you see fit but must use the volume name before `:`, not the path to the volume.
